"""empty message

Revision ID: 01fd6a81bce3
Revises: aebd9144004f
Create Date: 2025-04-11 19:10:31.235508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fd6a81bce3'
down_revision = 'aebd9144004f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_context().dialect.name
    if dialect == 'postgresql':
        op.drop_constraint('transactions_category_id_fkey', 'transactions', type_='foreignkey')
        op.create_foreign_key(
            'transactions_category_id_fkey',
            'transactions',
            'categories',
            ['category_id'],
            ['id'],
            ondelete='SET NULL'
        )
    else:
        with op.batch_alter_table('transactions', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_context().dialect.name
    if dialect == 'postgresql':
        op.drop_constraint('transactions_category_id_fkey', 'transactions', type_='foreignkey')
        op.create_foreign_key(
            'transactions_category_id_fkey',
            'transactions',
            'categories',
            ['category_id'],
            ['id']
        )
    else:
        with op.batch_alter_table('transactions', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
